name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore HolaMicroservicio/HolaMicroservicio.csproj

      - name: Build
        run: dotnet build HolaMicroservicio/HolaMicroservicio.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish HolaMicroservicio/HolaMicroservicio.csproj --configuration Release --no-build --output ./artifacts/publish
